#!/usr/bin/env bash
# =============================================================================
# Step 06a: Create a local bootstrap bundle for an unreachable edge worker.
#
# Usage:
#   bash scripts/06a-create-edge-bootstrap-bundle.sh "<edge-entry>" [output-dir]
#
# Run this on the management/XNAT side after step 05 has created the hosted
# k0s control plane and join token. Transfer the resulting tarball to the
# facility edge and run bootstrap-rsl60.sh there.
# =============================================================================
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/00-common.sh"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <edge-entry> [output-dir]"
    echo "  edge-entry format: CLUSTER_NAME|NODE_IP|SSH_USER|SSH_KEY|PROJECT_ID|ACCESS_KEY|SECRET_KEY"
    exit 1
fi

parse_edge_entry "$1"

OUT_DIR="${2:-${REPO_DIR}/secrets/edge-bootstrap-${CLUSTER_NAME}}"
ARCHIVE="${OUT_DIR}.tar.gz"

if [ ! -f "${REPO_DIR}/join-token-${CLUSTER_NAME}" ]; then
    echo "ERROR: ${REPO_DIR}/join-token-${CLUSTER_NAME} not found."
    echo "Run step 05 first:"
    echo "  bash scripts/05-setup-edge-cluster.sh '<edge-entry>'"
    exit 1
fi

if ! kubectl get secret -n "${CLUSTER_NAME}" "${CLUSTER_NAME}-ca" >/dev/null 2>&1; then
    echo "ERROR: k0smotron cluster CA secret '${CLUSTER_NAME}-ca' not found in namespace '${CLUSTER_NAME}'."
    echo "Run step 05 and wait for the hosted control plane to become Ready."
    exit 1
fi

echo "=== 06a: Creating local bootstrap bundle for ${CLUSTER_NAME} ==="
mkdir -p "${OUT_DIR}/haproxy"
rm -f "${OUT_DIR}/join-token" \
      "${OUT_DIR}/ais-edge-ca.crt" \
      "${OUT_DIR}/edge-bootstrap.env" \
      "${OUT_DIR}/bootstrap-rsl60.sh" \
      "${OUT_DIR}/README.md" \
      "${OUT_DIR}/haproxy/ca.crt" \
      "${OUT_DIR}/haproxy/server.pem"

cp "${REPO_DIR}/join-token-${CLUSTER_NAME}" "${OUT_DIR}/join-token"
chmod 0600 "${OUT_DIR}/join-token"

TMP_DIR=$(mktemp -d /tmp/ais-edge-bootstrap-XXXXXX)
cleanup() { rm -rf "${TMP_DIR}"; }
trap cleanup EXIT

HAPROXY_CA="${OUT_DIR}/haproxy/ca.crt"
HAPROXY_CAKEY="${TMP_DIR}/ca.key"
HAPROXY_KEY="${TMP_DIR}/haproxy-server.key"
HAPROXY_CSR="${TMP_DIR}/haproxy-server.csr"
HAPROXY_CRT="${TMP_DIR}/haproxy-server.crt"
HAPROXY_CONF="${TMP_DIR}/haproxy-server.cnf"

kubectl get secret -n "${CLUSTER_NAME}" "${CLUSTER_NAME}-ca" \
    -o jsonpath='{.data.tls\.crt}' | base64 -d > "${HAPROXY_CA}"
kubectl get secret -n "${CLUSTER_NAME}" "${CLUSTER_NAME}-ca" \
    -o jsonpath='{.data.tls\.key}' | base64 -d > "${HAPROXY_CAKEY}"

cat > "${HAPROXY_CONF}" <<EOF
[req]
distinguished_name=req
req_extensions=v3_req
[v3_req]
subjectAltName=@alt
[alt]
DNS.1=localhost
DNS.2=kubernetes
DNS.3=kubernetes.default
DNS.4=kubernetes.default.svc
DNS.5=kubernetes.default.svc.cluster.local
IP.1=127.0.0.1
IP.2=10.96.0.1
EOF

if [[ "${NODE_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || [[ "${NODE_IP}" == *:* ]]; then
    echo "IP.3=${NODE_IP}" >> "${HAPROXY_CONF}"
elif [ -n "${NODE_IP}" ]; then
    echo "DNS.6=${NODE_IP}" >> "${HAPROXY_CONF}"
fi

openssl genrsa -out "${HAPROXY_KEY}" 2048 2>/dev/null
openssl req -new -key "${HAPROXY_KEY}" -subj "/CN=k0smotron-haproxy" \
    -out "${HAPROXY_CSR}" -config "${HAPROXY_CONF}" 2>/dev/null
openssl x509 -req -in "${HAPROXY_CSR}" -CA "${HAPROXY_CA}" -CAkey "${HAPROXY_CAKEY}" \
    -CAcreateserial -out "${HAPROXY_CRT}" -days 3650 \
    -extensions v3_req -extfile "${HAPROXY_CONF}" 2>/dev/null
cat "${HAPROXY_CRT}" "${HAPROXY_KEY}" > "${OUT_DIR}/haproxy/server.pem"
chmod 0644 "${OUT_DIR}/haproxy/ca.crt"
chmod 0600 "${OUT_DIR}/haproxy/server.pem"

if [ -f "${REPO_DIR}/ais-edge-ca.crt" ]; then
    cp "${REPO_DIR}/ais-edge-ca.crt" "${OUT_DIR}/ais-edge-ca.crt"
    chmod 0644 "${OUT_DIR}/ais-edge-ca.crt"
else
    echo "WARNING: ${REPO_DIR}/ais-edge-ca.crt not found; run 02b before creating final bundles."
fi

cp "${REPO_DIR}/scripts/edge-local-bootstrap.sh" "${OUT_DIR}/bootstrap-rsl60.sh"
chmod 0755 "${OUT_DIR}/bootstrap-rsl60.sh"

q() { printf "%q" "$1"; }
EDGE_DATA_HOST_PATH="${EDGE_DATA_HOST_PATH:-/data/xnat-ingest}"
EDGE_ORTHANC_STORAGE_HOST_PATH="${EDGE_ORTHANC_STORAGE_HOST_PATH:-${EDGE_DATA_HOST_PATH}/orthanc-storage}"
EDGE_K0S_DATA_DIR="${EDGE_K0S_DATA_DIR:-/data/k0s}"

{
    echo "# Generated by scripts/06a-create-edge-bootstrap-bundle.sh"
    echo "export CLUSTER_NAME=$(q "${CLUSTER_NAME}")"
    echo "export NODE_IP=$(q "${NODE_IP}")"
    echo "export INSTALL_TOPOLOGY=$(q "${INSTALL_TOPOLOGY:-onprem}")"
    echo "export MGMT_NODE_IP=$(q "${MGMT_NODE_IP:-}")"
    echo "export SEAWEEDFS_HOSTNAME=$(q "${SEAWEEDFS_HOSTNAME}")"
    echo "export K0S_API_HOSTNAME=$(q "${K0S_API_HOSTNAME}")"
    echo "export KONNECTIVITY_HOSTNAME=$(q "${KONNECTIVITY_HOSTNAME}")"
    echo "export INGRESS_PORT=$(q "${INGRESS_PORT}")"
    echo "export EDGE_ORTHANC_MODE=$(q "${EDGE_ORTHANC_MODE:-managed}")"
    echo "export EDGE_DATA_HOST_PATH=$(q "${EDGE_DATA_HOST_PATH}")"
    echo "export EDGE_ORTHANC_STORAGE_HOST_PATH=$(q "${EDGE_ORTHANC_STORAGE_HOST_PATH}")"
    echo "export EDGE_K0S_DATA_DIR=$(q "${EDGE_K0S_DATA_DIR}")"
    echo "export EDGE_ORTHANC_URL=$(q "${EDGE_ORTHANC_URL:-http://orthanc.xnat-ingest.svc.cluster.local:8042}")"
} > "${OUT_DIR}/edge-bootstrap.env"
chmod 0644 "${OUT_DIR}/edge-bootstrap.env"

cat > "${OUT_DIR}/README.md" <<EOF
# AIS Edge bootstrap bundle: ${CLUSTER_NAME}

This bundle is for a facility edge worker that the management/XNAT host cannot SSH into.

On the facility edge machine:

\`\`\`bash
tar xzf edge-bootstrap-${CLUSTER_NAME}.tar.gz
cd edge-bootstrap-${CLUSTER_NAME}
./bootstrap-rsl60.sh
\`\`\`

Then ask the management-side operator to run:

\`\`\`bash
KUBECONFIG=kubeconfig-${CLUSTER_NAME} kubectl get nodes -o wide
AIS_EDGE_NO_SSH=1 bash scripts/07-deploy-edge-ingest.sh '<edge-entry>'
\`\`\`

This bundle includes a k0s join token and haproxy private key. Delete it from
shared transfer locations after bootstrap.
EOF

tar -C "$(dirname "${OUT_DIR}")" -czf "${ARCHIVE}" "$(basename "${OUT_DIR}")"
chmod 0600 "${ARCHIVE}"

echo "Bundle directory: ${OUT_DIR}"
echo "Bundle archive:   ${ARCHIVE}"
echo ""
echo "Transfer the archive to ${NODE_IP} by a site-approved path, unpack it there,"
echo "and run ./bootstrap-rsl60.sh locally on the edge."
